spring:
  liquibase:
    enabled: true
    changelog: classpath:db/changelog/db.changelog.yaml
  datasource:
    url: jdbc:mysql://mysqldb:3306/playground_database?useSSL=false&createDatabaseIfNotExist=true
    username: myadmin
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
  servlet:
    context-path: /api