databaseChangeLog:
- changeSet:
    id: 1706537330630-1
    author: liquibase (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
            name: id
            type: INT
        - column:
            name: description
            type: VARCHAR(255)
        - column:
            name: name
            type: VARCHAR(255)
        tableName: playground

